// Generated by CoffeeScript 1.3.3
(function() {
  var __slice = [].slice;

  Meteor.ModularRouter = (function() {

    function ModularRouter(options) {
      var k, v, _ref,
        _this = this;
      console.log("New PathJSRouter.");
      if (((options != null ? options.routes : void 0) != null) && _.isObject(options.routes)) {
        console.log("Routes received", options.routes);
        _ref = options.routes;
        for (k in _ref) {
          v = _ref[k];
          console.log("mapping", k, v);
          Path.map(k.toString()).to(function() {
            console.log("routing to", k, v);
            return amplify.publish("route", v);
          });
        }
      }
    }

    ModularRouter.prototype.start = function() {
      console.log("Router starting.");
      return Path.listen();
    };

    return ModularRouter;

  })();

  Meteor.PageTurner = (function() {

    function PageTurner(options) {
      console.log("New PageTurner.");
      amplify.subscribe("route", function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return console.log("PageTurner Route received", args);
      });
    }

    PageTurner.prototype.start = function() {
      return console.log("PageTurner starting.");
    };

    return PageTurner;

  })();

}).call(this);
